# Generated by Django 5.0.4 on 2024-04-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.CharField(max_length=100),
        ),
    ]
